services:
  - type: web
    name: face-recognition
    env: python
    plan: free
    buildCommand: |
      # System dependencies
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        cmake \
        pkg-config \
        libgl1-mesa-dev \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libx11-dev \
        python3-dev \
        python3-pip \
        python3-venv

      # Create directories
      mkdir -p backend/data backend/known_faces

      # Upgrade pip and install build tools
      python -m pip install --upgrade pip setuptools wheel

      # Install dependencies in order
      python -m pip install numpy
      python -m pip install cmake
      python -m pip install dlib
      python -m pip install -r requirements.txt

    startCommand: |
      cd backend
      python -m gunicorn --bind=0.0.0.0:10000 --workers=1 --timeout=120 app:app

    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PRODUCTION
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    healthCheckPath: /health
    healthCheckPath: /health
    autoDeploy: true
