services:
  - type: web
    name: face-recognition
    env: python
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: DISABLE_OPENCV_PARALLEL_BUILD
        value: "1"
    buildCommand: |
      # Install only essential system dependencies
      apt-get update
      apt-get install -y --no-install-recommends \
        build-essential \
        libgl1-mesa-glx \
        libglib2.0-0
      apt-get clean
      rm -rf /var/lib/apt/lists/*

      # Set environment variables for minimal memory usage
      export CFLAGS="-Os"
      export CXXFLAGS="-Os"
      export CMAKE_BUILD_PARALLEL_LEVEL=1
      export MAKEFLAGS="-j1"
      export FACE_RECOGNITION_DISABLE_GPU=1
      
      # Clear any existing pip cache
      pip cache purge
      rm -rf ~/.cache/pip
      
      # Upgrade pip with minimal dependencies
      pip install --no-cache-dir --upgrade pip

      # Install packages in small groups with cleanup between each
      
      # Install packages in order of dependency with minimal memory usage
      pip install --no-cache-dir numpy==1.24.3
      pip install --no-cache-dir Pillow==10.0.1
      pip install --no-cache-dir dlib==19.24.2 --no-deps
      pip install --no-cache-dir face-recognition==1.3.0 --no-deps
      pip install --no-cache-dir opencv-python-headless==4.8.1.78
      pip install --no-cache-dir Flask==2.3.3 Werkzeug==2.3.7 gunicorn==21.2.0
      pip install --no-cache-dir pymongo==4.5.0
      pip install --no-cache-dir pandas==2.0.3 --no-deps

      # Clean up all caches
      rm -rf ~/.cache/pip
      find /tmp -type f -delete
      
      # Group 4: OpenCV (headless)
      pip install --no-cache-dir opencv-python-headless==4.8.0
      pip cache purge
      
      # Group 5: Pandas (minimal install)
      pip install --no-cache-dir pandas==2.0.0
      pip cache purge
      
      # Group 6: Build and install dlib with minimal memory usage
      pip install --no-cache-dir setuptools wheel
      DLIB_USE_CUDA=0 pip install --no-cache-dir --no-deps dlib==19.24.0
      pip cache purge
      
      # Group 7: Face recognition (no deps to avoid reinstalling)
      pip install --no-cache-dir --no-deps face-recognition==1.3.0
      
      # Final cleanup
      pip cache purge
      rm -rf ~/.cache/pip
      rm -rf /tmp/*
      
    startCommand: |
      cd backend && gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
      - key: FLASK_ENV
        value: production
      - key: CMAKE_BUILD_PARALLEL_LEVEL
        value: "1"
      - key: MAKEFLAGS
        value: "-j1"
      - key: PIP_NO_CACHE_DIR
        value: "true"
      - key: CFLAGS
        value: "-O2"
    healthCheckPath: /health
    healthCheckPath: /health
    autoDeploy: true
