services:
  - type: web
    name: face-recognition
    env: python
    plan: free
    buildCommand: |
      # Install Python 3.9
      apt-get update
      apt-get install -y python3.9 python3.9-dev python3.9-venv

      # System libraries for OpenCV and dlib
      apt-get install -y \
        libgl1-mesa-dev \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev

      # Set up virtual environment
      python3.9 -m venv /opt/venv
      . /opt/venv/bin/activate

      # Upgrade pip and install wheel first
      pip install --upgrade pip wheel setuptools

      # Install all requirements
      pip install -r requirements.txt --no-cache-dir

      # Create necessary directories
      mkdir -p backend/data backend/known_faces

    startCommand: |
      . /opt/venv/bin/activate
      cd backend
      exec gunicorn --bind=0.0.0.0:10000 --workers=1 --timeout=120 app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PRODUCTION
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    healthCheckPath: /health
    healthCheckPath: /health
    autoDeploy: true
