services:
  - type: web
    name: face-recognition
    env: python
    buildCommand: |
      # System dependencies
      apt-get update && apt-get install -y \
        cmake \
        build-essential \
        pkg-config \
        libgl1-mesa-dev \
        libx11-dev \
        libopenblas-dev \
        liblapack-dev \
        libgtk-3-dev \
        python3-dev \
        python3.10-dev

      # Use system Python and pip
      python -m pip install --upgrade pip setuptools wheel

      # Install dependencies in order
      python -m pip install numpy==1.24.3
      python -m pip install --no-deps dlib==19.24.2
      python -m pip install --only-binary=:all: pandas==2.0.3
      python -m pip install -r requirements.txt
    startCommand: cd backend && gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    autoDeploy: true
