services:
  - type: web
    name: face-recognition
    env: python
    plan: free
    buildCommand: |
      # Install minimal system dependencies
      apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        libgl1-mesa-dev \
        python3-dev \
        && rm -rf /var/lib/apt/lists/*

      # Create minimal required directories
      mkdir -p backend/data backend/known_faces

      # Install dependencies with pip
      pip install --no-cache-dir -U pip setuptools wheel
      pip install --no-cache-dir numpy==1.21.6  # Install numpy first
      pip install --no-cache-dir -r requirements.txt

      # Clean up
      rm -rf ~/.cache/pip
      find . -type d -name __pycache__ -exec rm -r {} +

    startCommand: cd backend && exec gunicorn --bind=0.0.0.0:10000 --workers=1 --timeout=120 app:app

    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PRODUCTION
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    healthCheckPath: /health
    healthCheckPath: /health
    autoDeploy: true
