services:
  - type: web
    name: face-recognition
    env: python
    plan: free
    buildCommand: |
      # System dependencies
      apt-get update && apt-get install -y \
        python3.9 \
        python3.9-dev \
        python3.9-venv \
        cmake \
        build-essential \
        pkg-config \
        libgl1-mesa-dev \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libx11-dev

      # Create directories
      mkdir -p backend/data backend/known_faces

      # Create and activate venv
      python3.9 -m venv .venv
      . .venv/bin/activate

      # Install dependencies
      python3.9 -m pip install --upgrade pip wheel setuptools
      python3.9 -m pip install cmake
      python3.9 -m pip install -r requirements.txt

    startCommand: |
      . .venv/bin/activate
      cd backend
      gunicorn --bind 0.0.0.0:10000 --workers 1 app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PRODUCTION
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    healthCheckPath: /health
    autoDeploy: true
