services:
  - type: web
    name: face-recognition
    env: python
    buildCommand: |
      # System dependencies
      apt-get update && apt-get install -y \
        cmake \
        build-essential \
        pkg-config \
        libgl1-mesa-dev \
        libx11-dev \
        libopenblas-dev \
        liblapack-dev \
        libgtk-3-dev \
        python3-dev

      # Create and activate virtual environment
      python -m venv /opt/venv
      . /opt/venv/bin/activate

      # Install build dependencies
      pip install --upgrade pip setuptools wheel
      
      # Install numpy first (required for dlib)
      pip install numpy==1.24.3

      # Install dlib from pre-built wheel
      pip install --no-deps --only-binary :all: dlib==19.24.2

      # Install the rest of the requirements
      pip install -r requirements.txt

      # Deactivate virtual environment
      deactivate
    startCommand: |
      . /opt/venv/bin/activate
      cd backend && gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    autoDeploy: true
