services:
  - type: web
    name: face-recognition
    env: python
    buildCommand: |
      # System dependencies
      apt-get update && apt-get install -y \
        cmake \
        build-essential \
        pkg-config \
        libgl1-mesa-dev \
        libx11-dev \
        python3.9-dev

      # Upgrade pip and install basic build tools
      pip install --upgrade pip
      pip install wheel==0.40.0 setuptools==67.8.0

      # Install core dependencies first
      pip install numpy==1.21.6
      pip install dlib==19.22.1

      # Install the rest of the requirements
      pip install -r requirements.txt --no-deps
      pip install -r requirements.txt

    startCommand: cd backend && gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    autoDeploy: true
