services:
  - type: web
    name: face-recognition
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
