services:
  - type: web
    name: face-recognition
    env: python
    plan: free
    region: ohio
    buildCommand: |
      # System dependencies
      apt-get update && apt-get install -y \
        cmake \
        build-essential \
        pkg-config \
        libgl1-mesa-dev \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libx11-dev \
        python3.9-dev \
        python3.9-distutils

      # Create required directories
      mkdir -p backend/data backend/known_faces

      # Create and activate virtual environment
      python -m venv venv
      . venv/bin/activate

      # Install build tools and core dependencies
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install cmake==3.25.0 numpy==1.19.5 dlib==19.22.0

      # Install gunicorn and other web dependencies first
      python -m pip install gunicorn==20.1.0 flask==2.0.3 werkzeug==2.0.3

      # Install the project and remaining dependencies
      python -m pip install -e .

      # Verify gunicorn installation
      which gunicorn

    startCommand: |
      . venv/bin/activate && \
      cd backend && \
      gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PRODUCTION
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    healthCheckPath: /health
    autoDeploy: true
