services:
  - type: web
    name: face-recognition
    env: python
    buildCommand: |
      # System dependencies
      apt-get update
      apt-get install -y cmake build-essential pkg-config libgl1-mesa-dev

      # Ensure pip is available and up to date
      python -m ensurepip --upgrade
      python -m pip install --upgrade pip

      # Install Python packages
      pip install --no-cache-dir -r requirements.txt
    startCommand: cd backend && gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    autoDeploy: true
