services:
  - type: web
    name: face-recognition
    env: python
    plan: free
    region: ohio
    buildCommand: |
      # System dependencies
      apt-get update && apt-get install -y \
        cmake \
        build-essential \
        pkg-config \
        libgl1-mesa-dev \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libx11-dev \
        python3.9-dev \
        python3.9-distutils

      # Create and activate virtual environment with Python 3.9
      python3.9 -m venv venv
      . venv/bin/activate

      # Install build tools
      python -m pip install --upgrade pip setuptools wheel
      
      # Install build dependencies
      python -m pip install cmake==3.25.0

      # Install the project in editable mode
      python -m pip install -e .

    startCommand: |
      . venv/bin/activate
      cd backend && python -m gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PRODUCTION
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: face_recognition
    healthCheckPath: /health
    autoDeploy: true
